language: node_js
node_js:
  - '10'

env:
  IMAGE_NAME: luckjs/luck-api

stages:
#  - test
#  - build
  - deploy

jobs:
  include:
#    - stage: test
#      cache:
#        directories:
#          - node_modules
#      install:
#        - npm install mocha ts-node
#      script: npm run-script test
#    - stage: build
#      services:
#        - docker
#      script:
#        - docker build . -t $IMAGE_NAME
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#        - docker push $IMAGE_NAME
#        - docker ps
    - stage: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_a9d7ea149dca_key -iv $encrypted_a9d7ea149dca_iv
          -in luck_key.enc -out ./luck_key -d
      script: skip
      deploy:
        provider: script
        script: chmod 600 luck_key && ssh -o StrictHostKeyChecking=no -i ./luck_key $HOST_IP ./luck.org.pl/deploy.sh
