version: '3'
services:
  luck-api:
    environment:
    - .env
    image: ${PROD_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run watch
    container_name: ${PROD_CONTAINER_NAME}
    ports:
    - "${PROD_PORT}:${PROD_PORT_EXPOSE}"
    volumes:
    - "./:/var/${PROD_VOLUMES}"
    - "/var/${PROD_VOLUMES}/node_modules"
    depends_on:
    - "mongo"
  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
    - "${PROD_DATABASE_PORT}:${PROD_DATABASE_PORT}"
